name: Deploy Project
on:
  push:
    branches:
      - main
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.2.2
      - name: Node Setup
        uses: actions/setup-node@v4
        with:
          node-version: 20.16.0
      - name: Install Dependencies
        run: npm ci
      - name: Test Run
        run: npm test
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.2.2
      - name: Node Setup
        uses: actions/setup-node@v4
        with:
          node-version: 20.16.0
      - name: Install Dependencies
        run: npm ci
      - name: Build Project
        env:
          CI: false
        run: npm run build
      - name: Set up SSH private key
        run: |
          echo "${{ secrets.MY_EC2_KEY }}" > private-key.pem
          chmod 600 private-key.pem
      - name: Deploy to EC2
        # uses: appleboy/ssh-action@v0.1.5
        # with:
        #   host: ${{ vars.MY_EC2_PUBLIC_IP }}
        #   username: ec2-user
        #   key: ${{ secrets.MY_EC2_KEY }} # GitHub secret for private key
        run: |
          cat private-key.pem
          scp -i private-key.pem -r ./build/* ec2-user@${{ secrets.EC2_PUBLIC_IP }}:/usr/share/nginx/html/
          ssh -i private-key.pem ec2-user@${{ secrets.EC2_PUBLIC_IP }} "sudo systemctl restart nginx"
