name: Deploy Project
on:
  push:
    branches:
      - main
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.2.2
      - name: Node Setup
        uses: actions/setup-node@v4
        with:
          node-version: 20.16.0
      - name: Install Dependencies
        run: npm ci
      - name: Test Run
        run: npm test
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.2.2
      - name: Node Setup
        uses: actions/setup-node@v4
        with:
          node-version: 20.16.0
      - name: Install Dependencies
        run: npm ci
      - name: Build Project
        run: npm run build
      - name: Deploy
        run: echo
      - name: Deploy to EC2
        uses: appleboy/ssh-action@v0.1.5
        with:
          host: ${{ vars.MY_EC2_PUBLIC_IP }}
          username: ec2-user
          key: ${{ secrets.MY_EC2_KEY }} # GitHub secret for private key
          script:
            whoami
            # cd /path/to/your/project
            # sudo rm -rf /usr/share/nginx/html/*
            # cp -r /path/to/your/project/build/* /usr/share/nginx/html/
            # sudo systemctl restart nginx
