name: Sample Workflow
on: workflow_dispatch
jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: Step1
        run: echo "Hello!!!!!"
      - name: Step2
        run: |
          echo "Good"
          echo "Bye...."
