name: Test Run
on:
  push:
    branches:
      - main
jobs:
  test-build:
    runs-on: ubuntu-latest
    environment: dev
    outputs:
      artifact_name: ${{steps.NAME_GENERATER.outputs.artifact_name}}
    steps:
      - name: Checkout
        uses: actions/checkout@v4.2.2
      - name: Node Setup
        uses: actions/setup-node@v4
        with:
          node-version: 20.16.0
      - name: Install Dependencies
        run: npm ci
      - name: Test Project
        run: npm test
      - name: Build Project
        env:
          CI: false
        run: npm run build
      - name: List Files
        run: ls -l
      - id: NAME_GENERATER
        name: Generate artifact name
        run: |
          echo "START"
          echo ${{vars.BUILD_NUMBER}}
          echo BUILD_NUMBER=$((${{vars.BUILD_NUMBER}} + 1)) >> $GITHUB_ENV
          echo artifact_name=travel-guide@${{vars.BUILD_NUMBER}} >> $GITHUB_OUTPUT
          echo ${{vars.BUILD_NUMBER}} - $BUILD_NUMBER => $GITHUB_ENV
          echo "END"
      - name: Save Artifact
        uses: actions/upload-artifact@v4
        with:
          name: travel-guide@$BUILD_NUMBER
          overwrite: true
          path: build
  deploy:
    needs:
      - test-build
    runs-on: ubuntu-latest
    steps:
      - name: Get Build Artifact
        uses: actions/download-artifact@v4
        with:
          name: ${{needs.test-build.outputs.artifact_name}}
          path: build
      - name: List Files
        run: echo ${{needs.test-build.outputs.artifact_name}}
