name: Test Run
on:
  push:
    branches:
      - main
jobs:
  test:
    runs-on: ubuntu-latest
    environment: dev
    steps:
      - name: Checkout
        uses: actions/checkout@v4.2.2
      - name: Cache dependencies
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
      - name: Node Setup
        uses: actions/setup-node@v4
        with:
          node-version: 20.16.0
      - name: Install Dependencies
        run: npm ci
      - name: Test Project
        run: npm test
  build:
    runs-on: ubuntu-latest
    needs:
      - test
    environment: dev
    outputs:
      artifact_name: ${{steps.NAME_GENERATER.outputs.artifact_name}}
    steps:
      - name: Checkout
        uses: actions/checkout@v4.2.2
      - name: Cache dependencies
        uses: actions/cache@v2
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
      - name: Node Setup
        uses: actions/setup-node@v4
        with:
          node-version: 20.16.0
      - name: Install Dependencies
        run: npm ci
      - name: Test Project
        run: npm test
      - name: Build Project
        env:
          CI: false
        run: npm run build
      - name: List Files
        run: ls -l
      - id: NAME_GENERATER
        name: Generate artifact name
        run: |
          echo "START"
          echo "Initial BUILD_NUMBER: ${{ vars.BUILD_NUMBER }}"

          # Increment BUILD_NUMBER and write it to $GITHUB_ENV
          next_build_number=$(( ${{ vars.BUILD_NUMBER }} + 1 ))
          echo "BUILD_NUMBER=$next_build_number" >> $GITHUB_ENV

          # Set artifact_name as an output
          echo "artifact_name=travel-guide@$next_build_number" >> $GITHUB_OUTPUT

          # Check the contents of $GITHUB_ENV (to verify if the variable was set correctly)
          cat $GITHUB_ENV

          echo "Updated Build Number: $next_build_number"
          echo "END"
      - name: Check ENV
        run: echo "BUILD_NUMBER=$BUILD_NUMBER"
      - name: Save Artifact
        uses: actions/upload-artifact@v4
        with:
          name: travel-guide@${{env.BUILD_NUMBER}}
          overwrite: true
          path: build
  deploy:
    needs:
      - build
    runs-on: ubuntu-latest
    steps:
      - name: Get Build Artifact
        uses: actions/download-artifact@v4
        with:
          name: ${{needs.test-build.outputs.artifact_name}}
          path: build
      - name: List Files
        run: echo ${{needs.test-build.outputs.artifact_name}}
