name: Test Run
on:
  push:
    branches:
      - main
jobs:
  test-build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.2.2
      - name: Node Setup
        uses: actions/setup-node@v4
        with:
          node-version: 20.16.0
      - name: Install Dependencies
        run: npm ci
      - name: Test Project
        run: npm test
      - name: Build Project
        env:
          CI: false
        run: npm run build
      - name: List Files
        run: ls -l
      - name: Save Artifact
        uses: actions/upload-artifact@v4
        with:
          # Name of the artifact to upload.
          # Optional. Default is 'artifact'
          name: travel-guide@1.0.0
          overwrite: true
          # A file, directory or wildcard pattern that describes what to upload
          # Required.
          path: build
  deploy:
    needs:
      - test-build
    runs-on: ubuntu-latest
    steps:
      - name: Get Build Artifact
        uses: actions/download-artifact@v4
        with:
          name: travel-guide@1.0.0
      - name: List Files
        run: ls -l
